### ISSUE TITLE
Human evaluation code

### ISSUE THREAD

**Issue by vzhong** [facebookresearch/end-to-end-negotiator#10]
Hi folks,

First off, I really enjoyed reading this paper and I think this is a promising technique for developing dialog agents. I wanted to ask how one can reproduce the human evaluation results from the paper. Obviously, exact reproducibility is impossible due to the nature of the human annotators. But is the evaluation script available? Do you release scripts to facilitate the process of playing against human opponents and collecting the results of the negotiation?

**Comment by denisyarats** [comment]
Hey,

We don't provide scripts that we used to run human evaluation, as they depend on some internal infrastructure, but you can take a look at `chat.py` which is very close to what we used to perform human evaluation.
