### ISSUE TITLE
training: value cannot be converted without overflow

### ISSUE THREAD

**Issue by ra312** [facebookresearch/end-to-end-negotiator#18]
Dear Community
I have the following message during python train.py
"Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main()
  File "train.py", line 98, in main
    train_loss, valid_loss, select_loss = engine.train(corpus)
  File "/Users/ra312/Documents/GitHub/end-to-end-negotiator/src/engine.py", line 195, in train
    if valid_select_loss < best_valid_select_loss:
RuntimeError: value cannot be converted to type float without overflow: 10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815104.000000"
 I did as instructed. Any help is appreciated.
I launched train.py in condo environment py30. In this environment, I installed two packages:PyTorch and Visdom. The operating system is  MacOs High Sierra 10.13.4

**Comment by denisyarats** [comment]
Hi, could you please share the train arguments?

**Comment by ra312** [comment]
Dear 1nadequacy. I just typed python train.py. Reading the instructions, I could not see any mention of arguments. Looking through the repository directories I could not see possible argument files. I just want to see how different parameters will play out. Thanks for your help.

**Comment by LucyLu717** [comment]
It seemed that the problem is the initial value of best_valid_select_loss which is 1e+100 and beyond the scope of a float. I changed it to a smaller value and the program is able to run without error.

**Comment by ra312** [comment]
Dear LucyLu717. Can you share your commit? I could not see it in the repo. Thanks.

**Comment by LucyLu717** [comment]
I did the change locally. It's (around) line 187 in the method "train" in engine.py. I changed 1e100 to 1e20.

**Comment by denisyarats** [comment]
@LucyLu717 thanks for fixing it, feel free to send a PR.
