### ISSUE TITLE
CUDA not available. Unable to train

### ISSUE THREAD

**Issue by ishwara-bhat** [facebookresearch/end-to-end-negotiator#19]
Hi,
when I run 
"python train.py --data data/negotiate --cuda --bsz 16 --clip 0.5 --decay_every 1 --decay_rate 5.0 --dropout 0.5 --init_range 0.1 --lr 1 --max_epoch 30 --min_lr 0.01 --momentum 0.1 --nembed_ctx 64 --nembed_word 256 --nesterov --nhid_attn 256 --nhid_ctx 64 --nhid_lang 128 --nhid_sel 256 --nhid_strat 128 --sel_weight 0.5 --model_file sv_model.th"

I get the assertion fail error that CUDA not available.  I do not have GPU on my machine. CUDA wont work due to that.

Is there any way forward for training without GPU? 

Thanks for the help.

**Comment by denisyarats** [comment]
Hi, if you don't have GPU on your machine, then you should remove --cuda flag from your arguments.
