### ISSUE TITLE
Expecting torch.Longtensor but found type torch.Inttensor

### ISSUE THREAD

**Issue by hegebharat** [facebookresearch/end-to-end-negotiator#20]
In Moules.py file Line no 107 and 108 only 2 arguments are passed. 
        cnt = ctx.index_select(0, cnt_idx)
        val = ctx.index_select(0, val_idx)

But as per documentation (https://pytorch.org/docs/stable/torch.html) 3 arguments are passed.
I am getting below error. 
"RunTimeError: Expected object of type torch.Longtensor but  found of type torch.Inttensor ".
I try to typecast it as follows: cnt = ctx.index_select(0, torch.Longtensor(cnt_idx)). But still got the same error.

I am using python 3.7 . So what might be the issue?

Thanks

**Comment by LucyLu717** [comment]
I'm using python 3.6 and got the same error. I cast cnt_idx by cnt_idx = cnt_idx.type(torch.LongTensor) and it seemed to work.

**Comment by LucyLu717** [comment]
I found later that the version of PyTorch (0.4) is the issue there. Switching to PyTorch 0.3.1 without changing the code would also solve the problem.

**Comment by LucyLu717** [comment]
I found later that the version of PyTorch (0.4) may be the issue here. Switching to PyTorch 0.3.1 without changing the code would also solve the problem.
