### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by SarimShehzad** [facebookresearch/end-to-end-negotiator#23]
Hi, 
I'm new to artificial intelligence, machine learning and also python. I tried to implement this research as a part of my final dissertation on CentOS 7. After installing anaconda and all other tools and dependencies, when i executed "train.py" file, it took about 20 minutes, and finished fine. But then after I tried to look for where it has saved the trained model , I couldnt find it.
I wanted to chat with it myself so I executed "chat.py", but it gave me an error saying 
"utils.py line 35
with open(file_name, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType"
I dont know if I was supposed to make any changes in the code or not, please let me know if I need to and also where?
Thank you.

**Comment by SarimShehzad** [comment]
I was making a mistake in the config.py file, after correcting it, I was successfully able to use the chat.py.

**Comment by CatherineWong1** [comment]
>           I was making a mistake in the config.py file, after correcting it, I was successfully able to use the chat.py.
Hi ,I'm also new to AI. So I wanna ask you how you fix this mistake? Thank u.

**Comment by denisyarats** [comment]
Great, good to know.

**Comment by r8025n** [comment]
so what did you change that corrected it?
