### ISSUE TITLE
Human chat with full model 

### ISSUE THREAD

**Issue by rzhao1** [facebookresearch/end-to-end-negotiator#27]
Hi,

I have two questions:

1. How can I make human chat with full model version. I noticed that chat.py is disabled. 
2. The dialogues generated by full model version is very short, even shorter than original RNN version. What is the reason? 

Look forward to your reply!

**Comment by denisyarats** [comment]
Hi,

1) The chat.py does not support using the full model yet, but it should be straightforward to add. 
2) Perhaps the training parameters are not optimal. But in general, as stated in the paper (Table 5), the dialogues from the full model tend to be slightly shorter.

**Comment by rzhao1** [comment]
Thank you fro your reply!

I remembered the "old negotiation model" normally generate 6.6 turns per dialogues. How about the "full model"?

**Comment by denisyarats** [comment]
With RL or Rollouts it should be generating at least 5 turns on average.
