### ISSUE TITLE
pytorch0.4.1 does work for me

### ISSUE THREAD

**Issue by ryz1** [facebookresearch/end-to-end-negotiator#28]
pytorch0.4.1 does work for me, but pytorch1.0.0 works. when I use 0.4.1, it shows "mean is not a valid value for reduction" (it should be "elementwise_mean" in 0.4.1)

**Comment by denisyarats** [comment]
Hi, you are right, it should be pytorch 1.0.0 in the description, I actually tested it only on the 1.0.0. version, not on 0.4.1. I updated the README file.

As for you, you can either update your pytorch, or change the incompatibilities manually to accommodate pytorch 0.4.1.
