### ISSUE TITLE
dead code reported by vulture

### ISSUE THREAD

**Issue by RJ722** [facebookresearch/end-to-end-negotiator#3]
We used vulture (https://github.com/jendrikseipp/vulture) to search
for unused code in your project. You can find the report below. It 
would be great if you could give us feedback about which items are 
actually used or unused. This would allow us to improve vulture and
ideally it also helps you to remove obsolete code or even find typos 
and bugs.

### Command:
```
vulture end-to-end-negotiator/src
```

### Raw results:
```
end-to-end-negotiator/src/agent.py:12: Unused import 'autograd'
end-to-end-negotiator/src/metric.py:156: Unused function 'register_similarity'
end-to-end-negotiator/src/models/dialog_model.py:54: Unused attribute 'weight_ih'
end-to-end-negotiator/src/models/dialog_model.py:55: Unused attribute 'weight_hh'
end-to-end-negotiator/src/models/dialog_model.py:56: Unused attribute 'bias_ih'
end-to-end-negotiator/src/models/dialog_model.py:57: Unused attribute 'bias_hh'
end-to-end-negotiator/src/models/dialog_model.py:92: Unused function 'set_device_id'
end-to-end-negotiator/src/models/modules.py:27: Unused function 'init_rnn_cell'
end-to-end-negotiator/src/utils.py:15: Unused function 'backward_hook'
end-to-end-negotiator/src/utils.py:49: Unused function 'prob_random'
end-to-end-negotiator/src/utils.py:70: Unused variable 'e'
```

### Obvious false-positives:
```
end-to-end-negotiator/src/utils.py:70: Unused variable 'e'
```
Please have a look at: https://github.com/jendrikseipp/vulture/issues/51

### Unused code:
```
end-to-end-negotiator/src/agent.py:12: Unused import 'autograd'
```

There might be false positives, which can be prevented by adding them to a
whitelist file. You may find more info [here](https://github.com/jendrikseipp/vulture#usage)

Regards,
vulture team

**Comment by denisyarats** [comment]
Thanks!
